git:
  auth_method: none      # Git personal access token 사용 안 함
  timeout: 30

grading:
  timeout: 30
  max_concurrent: 5
  num_of_problems: 3     # 과제 총 과제 갯수

scheduler:
  pull_interval: 60     # Git pull 주기 (초)
  grade_interval: 60

server:
  host: 0.0.0.0
  port: 8000
  reload: false